//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebay.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        [Required]
        [Display(Name ="Müþteri Numarasý")]
        public string CustomerID { get; set; }

        [Required]
        [Display(Name = "Þirket Adý")]
        public string CompanyName { get; set; }

        [Required]
        [Display(Name = "Müþteri Adý")]
        public string ContactName { get; set; }

        [Required]
        [Display(Name = "Müþteri Açýklamasý")]
        public string ContactTitle { get; set; }

        [Required]
        [Display(Name = "Müþteri Numarasý")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Adres")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Þehir")]
        public string Region { get; set; }

        [Required]
        [Display(Name = "Bölge")]
        public string PostalCode { get; set; }

        [Required]
        [Display(Name = "Posta Kodu")]
        public string Country { get; set; }

        [Required]
        [Display(Name = "Ülke")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "Telefon")]
        public string Fax { get; set; }

        [Required]
        [Display(Name = "Kullanýcý Adý")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Þifre")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Kullanýcý Tipi")]
        public string UserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
    
}
