//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebay.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order_Details
    {
        [Display(Name ="Þipariþ Numarasý")]
        public int OrderID { get; set; }
        [Display(Name = "Ürün Numarasý")]
        public int ProductID { get; set; }
        [Display(Name = "Birim Fiyat")]
        public decimal UnitPrice { get; set; }
        [Display(Name = "Miktar")]
        public short Quantity { get; set; }
        [Display(Name = "Ýndirim")]
        public float Discount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
