//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebay.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Suppliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppliers()
        {
            this.Products = new HashSet<Products>();
        }
        [Display(Name ="Tedarikçi Numarasý")]
        public int SupplierID { get; set; }
        [Display(Name = "Þirket Adý")]
        public string CompanyName { get; set; }
        [Display(Name = "Tedarikçi Ýsmi")]
        public string ContactName { get; set; }
        [Display(Name = "Tedarikçi Ünvan")]
        public string ContactTitle { get; set; }
        [Display(Name = "Adres")]
        public string Address { get; set; }
        [Display(Name = "Þehir")]
        public string City { get; set; }
        [Display(Name = "Bölge")]
        public string Region { get; set; }
        [Display(Name = "Posta Kodu")]
        public string PostalCode { get; set; }
        [Display(Name = "Ülke")]
        public string Country { get; set; }
        [Display(Name = "Telefon")]
        public string Phone { get; set; }
        [Display(Name = "Fax")]
        public string Fax { get; set; }
        [Display(Name = "Ýnternet Sitesi")]
        public string HomePage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
